server:
  port: 8081
spring:
  application:
    name: chatBackend

wxlogin:
  app-id: ${wx_test_id}
  app-secret: ${wx_test_secret}
  api-prefix: /wxlogin
  verify-path: /wxverify

config:
  apiKey: ${baiduERNIE_KEY}
  secretKey: ${baiduERNIE_SECRET}

logging:
  org:
    springframework:
      web: DEBUG
  file:
    name: chat.log
  level:
    root: INFO
