server:
  port: 8081
spring:
  application:
    name: chatBackend
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
  web:
    resources:
      static-locations: classpath:/templates/,classpath:/static/

wxlogin:
  app-id: ${wx_test_id}
  app-secret: ${wx_test_secret}
  api-prefix: /wxlogin
  verify-path: /wxverify

baiduConfig:
  apiKey: ${baiduERNIE_KEY}
  secretKey: ${baiduERNIE_SECRET}

deepSeekConfig:
  apiKey: ${allenDeepSeek}

logging:
  org:
    springframework:
      web: DEBUG
  file:
    name: chat.log
  level:
    root: INFO
